# Generated by Django 4.1.1 on 2022-10-10 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User_detail",
            new_name="Userdetail",
        ),
    ]
