# Generated by Django 4.1.1 on 2022-10-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_detail_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_detail",
            name="user",
            field=models.CharField(default="", max_length=255),
        ),
    ]
