# Generated by Django 4.1.1 on 2022-10-10 04:31

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userdetail_about_you"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetail",
            name="country",
            field=django_countries.fields.CountryField(default="", max_length=2),
        ),
    ]
