# Generated by Django 4.1.1 on 2022-10-11 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_detail_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_detail",
            old_name="user",
            new_name="username",
        ),
    ]
