# Generated by Django 4.1.1 on 2022-10-10 04:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userdetail_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdetail",
            name="about_you",
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="country",
            field=django_countries.fields.CountryField(default="Nigeria", max_length=2),
        ),
    ]
