# Generated by Django 4.1.1 on 2022-10-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_detail_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_detail",
            name="username",
            field=models.CharField(default="", max_length=255),
        ),
    ]
