# Generated by Django 4.1.1 on 2022-10-10 04:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_userdetail_about_you_alter_userdetail_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
