# Generated by Django 4.1.1 on 2022-10-15 07:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_detail_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="", max_length=255)),
                ("first_name", models.CharField(default="", max_length=255)),
                ("last_name", models.CharField(default="", max_length=255)),
                ("email", models.EmailField(default="", max_length=255)),
                ("date", models.DateField(default="")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHERS", "Prefer not to say"),
                        ],
                        default="",
                        max_length=255,
                    ),
                ),
                (
                    "tel",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
            ],
        ),
    ]
