# Generated by Django 4.1.1 on 2022-10-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_userdetail_country_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Userdetail",
            new_name="User_detail",
        ),
    ]
