# Generated by Django 4.1.1 on 2022-10-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_viewdetails"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ViewDetails",
        ),
        migrations.AddField(
            model_name="user_detail",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
