# Generated by Django 4.1.1 on 2022-10-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_delete_viewdetails_user_detail_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_detail",
            name="slug",
        ),
    ]
