# Generated by Django 4.1.1 on 2022-10-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_rename_userdetail_user_detail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_detail",
            old_name="middle_name",
            new_name="other_name",
        ),
    ]
