# Generated by Django 4.1.1 on 2022-10-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_rename_middle_name_user_detail_other_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_detail",
            name="gender",
            field=models.CharField(
                choices=[
                    ("MALE", "Male"),
                    ("FEMALE", "Female"),
                    ("OTHERS", "Prefer not to say"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
