# Generated by Django 4.1.1 on 2022-10-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_user_detail_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_detail",
            name="id",
        ),
        migrations.AlterField(
            model_name="user_detail",
            name="username",
            field=models.CharField(
                default="", max_length=255, primary_key=True, serialize=False
            ),
        ),
    ]
