# Generated by Django 4.1.1 on 2022-10-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_user_detail_id_alter_user_detail_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_detail",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
    ]
