# Generated by Django 4.1.1 on 2022-10-10 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_user_detail_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_detail",
            name="other_name",
        ),
    ]
