# Generated by Django 4.1.1 on 2022-10-11 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
